### PR TITLE
Add a pwhash example

### PR DESCRIPTION
**Pull request by richchurcher**
Hi @paixaop and thanks for your hard work on node-sodium!

I've been working with it a bit recently, and thought the README could benefit from a pwhash example as I imagine many people will be interested in it for that purpose. Would be happy to contribute more documentation as time allows.

### CODE REVIEW

**Comment by richchurcher** [comment]
If you'd prefer this under the low-level section let me know and I'll amend.

**Comment by paixaop** [comment]
@richchurcher Documentation is always welcome. It would be better If you add a pwhash.md file under docs. You can also add a code sample under examples and will merge them in.

**Comment by richchurcher** [comment]
Will do!

**Comment by richchurcher** [comment]
Closing, will open another when docs are ready.

**Pull request closed without merging**
