### PR TITLE
fixed package.json allowing npm to build libsodium

### PR DESCRIPTION
**Pull request by ang-st**
Hello,
this is a quick fix for https://github.com/paixaop/node-sodium/issues/39

### CODE REVIEW

**Comment by paixaop** [comment]
thank you for the contribution. I will merge it if it compiles on travis, if you see the report the build is failing.

**Comment by ang-st** [comment]
hmm i didn't properly test after ```npm install``` and code actually fail at  when module required i'm looking why now

**Comment by ang-st** [comment]
what  ```var binding = require('../build/Release/sodium');``` is refering to ?
i suspect the Makefile is lacking something

**Comment by paixaop** [comment]
Thank you @ang-st !

**Pull request merged**
