### PR TITLE
replace V8 Object.Set with ForceSet

### PR DESCRIPTION
**Pull request by donpark**
Don't know why this part of my changes were left out but `node-sodium` won't build in io.js without this.

### CODE REVIEW

**Comment by paixaop** [comment]
i merged these changes, plus the newer version of libsodium into the develop branch. can you try it and see if it works and compiles fine

**Comment by donpark** [comment]
No need to test. I made these changes to `master` branch because `develop` branch failed to build to some gyp related issues.

**Comment by paixaop** [comment]
Don

try to run make configure before make sodium to generate the right files 
for gyp to work.
I added the logic to grab the libsodium defines automatically from the 
makefiles

Should be working, but please try it out.

Pedro

**Comment by donpark** [comment]
Will do later. My pants is on fire for the next few weeks.

**Pull request closed without merging**
