### PR TITLE
Detached signatures

### PR DESCRIPTION
**Pull request by jonasfj**
Cherry-picked in detached signatures from @BatikhSouri.
Ported it to node 0.11 and exposed it through public API... And added tests.

This is built ontop of my other PRs...

Oh, I also added 0.11 to travis.yml for testing.

Note, it'll probably be easier to read this PR once the other have landed.

### CODE REVIEW

**Comment by paixaop** [comment]
porting to 0.11 and 0.12 done, as well as detached signatures. Check the develop branch and let me know if it's working for you.

**Comment by jonasfj** [comment]
The `develop` branch doesn't work for me... Something with `node-sodium/deps/libsodium.gyp` missing on `npm install`..

**Comment by jonasfj** [comment]
But thanks for merging in these changes... node 0.12 support is awesome. As is detected signature and  fromSeed.. :)

**Comment by paixaop** [comment]
Jonas

should work now. I've changed the build system to be a bit smarter and 
detect the architecures and libsodium defines.
Please re run make sodium and it should run make configure also if it 
does not find the libsodium.gyp, or manually run make configure any time 
to regenerate the files.

Pedro

**Pull request closed without merging**
