### PR TITLE
add secretbox_easy and secretbox_open_easy

### PR DESCRIPTION
**Pull request by dominictarr**
fixes https://github.com/paixaop/node-sodium/issues/44

### CODE REVIEW

**Comment by paixaop** [comment]
@dominictarr can you write the tests for the new functions? I will merge them in.

**Comment by dominictarr** [comment]
Okay I added tests. Rather than just copy-paste the old tests i rewrote them so that less code was required.

**Comment by dominictarr** [comment]
oops, just realized I left a change out. This passes now.

**Comment by dominictarr** [comment]
hey is this okay is there anything you would like me to change about this?

**Pull request merged**
