### PR TITLE
Use node's assert module instead of should.js for runtime assertions

### PR DESCRIPTION
**Pull request by joshuaconner**
should.js modifies Object.prototype, and so making it a non-dev dependency will break the tests on apps that use another `should` for their testing, like the one chai provides. This replaces all of the `should` calls in node-sodium with their `assert` equivalents and makes should.js a dev dependency.

### CODE REVIEW

**Comment by etreworgy** [comment]
+1 This is critical as your library currently breaks my tests.  Should.js is designed to be used only as a dev dependency.

**Comment by paixaop** [comment]
Guys, why is should just for development?

**Comment by paixaop** [comment]
If this PR has a clean merge I will merge it the master

**Comment by joshuaconner** [comment]
Should merge cleanly now!

**Comment by etreworgy** [comment]
'should' is just for development because it makes changes to the Object.prototype.  This is fine when you're running your own tests internally.  If you include it as a regular dependency anybody that uses your library is going to inherit the same modifications to the Object.prototype.  This is very intrusive and can (and does) cause conflicts and unexpected behavior with other libraries and user's code.

In my case I use Chai.should in my own tests, but Chai.should got wiped out by 'should''s Object manipulation.

**Comment by paixaop** [comment]
swordfeng create a pull request I'll merge it

**Pull request merged**
