### PR TITLE
submodularize and update gyp for libsodium 1.0.10

### PR DESCRIPTION
**Pull request by reqshark**
this basically deletes the libsodium dep and turns it into a git submodule

we can checkout the upstream as part of configure step (if submodule is already checked out locally, git ignores that update command)

However, the PR is incomplete, since i think some stuff has to be changed in `sodium.cc` before the module will load symbols correctly

Maybe we could checkout a release version instead? Like libsodium 1.0.9? I could change this PR if there's any interest in that and wonder whether you think this sort of thing would make it easier to manage upstream version changes

### CODE REVIEW

**Comment by reqshark** [comment]
oh cool, the 1.0.10 release is here :)  

and woah this diff is like impossible to read on github, sorry about that..

**Comment by paixaop** [comment]
Thank you for the contribution. I've never favored this approach because changes to Libsodium that cause any compatibility issues will break node sodium. With a fixed version we can keep it working while we update, change, test newer versions of libsodium.

**Comment by reqshark** [comment]
> I've never favored this approach because changes to Libsodium that cause any compatibility issues will break node sodium

that makes sense. btw i was inspired by your work on `defines.js` and basically took that idea slightly further using a generic `gyp.am` file, here's the basic idea, which I learned from node-sodium: 
* automatic gyp generation of c sources, cflags, xcode_settings, defines

the rationale for such a thing would be to ease node binding compiler upkeep for upstream changes

an example gyp.am:
```python
{
    'targets': [
        {
            'target_name': '{LIB}',
            'variables': { 'target_arch%': '{ARCH}' },
            'type': 'static_library',
            'dependencies': [],
            'defines': [{DEFINES}],
            'include_dirs': [{INCLUDES}],
            'xcode_settings': { 'OTHER_CFLAGS': [{CFLAGS}], },
            'cflags': [{CFLAGS}],
            'ldflags': [{LDFLAGS}],
            'sources': [{SOURCES}],
        }
    ]
}
```

an example `configure.js` based on node-sodium's `defines.js`:
```js
/**
 * node configure
 * --------------
 *
 * automatic gyp generation of c sources, cflags, xcode_settings, defines
 * some machine specifics available in post ./configure file:
 *   • config.log
 *   • others found in Makefile.am
 *
 */

const readFileSync  = require('fs').readFileSync
const readdirSync   = require('fs').readdirSync
const writeFile     = require('fs').writeFile
const readFile      = require('fs').readFile

ø=[
  'libsodium',
  'libmill'
].map(lib => {
  readFile(`${lib}/config.log`, 'utf8', (err, l) => {
    var f = l.split(/## Output variables. ##/)[1].split(/## confdefs.h. ##/)

    var gyp = readFileSync('gyp.am', 'utf8')
    var gypi = require(`./${lib}.gypi`)
    for (var i in gypi) {
      var I = i.toUpperCase()
      var reg = new RegExp('\\{'+I+'\\}', 'gi')
      gyp = gyp.replace( reg, '{'+I+'}'+', \''+ gypi[i].join('\',\'') + '\'' )
    }

    var s = sources(lib)

    switch (lib) {
      case 'libmill':
        if (process.platform !== 'darwin')
          s[1] += `'-lanl', '-lrt',`
        break
    }

    gyp = gyp.replace(/{LIB}/g, lib)
    gyp = gyp.replace(/{ARCH}/g, require('os').arch())
    gyp = gyp.replace(/{INCLUDES}/g, includes(lib))
    gyp = gyp.replace(/{LDFLAGS}/g, ldflags(f[0]))
    gyp = gyp.replace(/{SOURCES}/g, s[0] )
    gyp = gyp.replace(/{CFLAGS}/g, (s[1] ? s[1] : '') + cflags(f[0]) )
    gyp = gyp.replace(/{DEFINES}/g, defs(f[1]))

    writeFile (`${lib}.gyp`, gyp )
  })
})

function sources (o) {
  var src = readdirSync(o), dir = {}
  if (src.filter(i => i === 'src').length) {
    dir.path = `${o}/src`
    src = readdirSync(dir.path)
  } else {
    dir.path = o
  }
  dir.src = src
  return make(dir)
}

function make (dir) {
  if (dir.src.filter(i => i === 'Makefile.am').length) {
    var file = readFileSync(`${dir.path}/Makefile.am`, 'utf8')
    var subdirs = file.match(/SUBDIRS/)
    if (subdirs) {
      var f = file.match(/\S+$/gm)
      f.shift()
      dir.path += `/${f}`
      file = readFileSync(`${dir.path}/Makefile.am`, 'utf8')
    }
    return readMakefile(file, dir.path)
  }
}

function readMakefile (f, root) {
  var read = 0, sources = '', cflags = '', rd, s
  var srcs = f.split(/la_SOURCES/)
  while (srcs.length - 1) {
    var src = srcs.pop()
    src = src.split(/\n/)
    while (++read) {
      rd = src[read]
      if (rd) {
        rd = rd.match(/(\S.*?)\.c/g)
        if (rd)
          sources += '\'' + root + '/' + rd + '\','
      } else {
        read = -1
      }
    }
  }

  var flags = f.split(/la_CFLAGS/)
  srcs = flags.length-1 ? flags[1].split(/\n/) : flags
  while (++read) {
    rd = srcs[read]
    if (rd) {
      rd = rd.split(/\\/)[0].replace(/^\s+/g,'')
      if (rd)
        cflags += '\'' + rd + '\','
    } else {
      read = -1
    }
  }
  return [sources, cflags]
}

function includes (lib) {
  var ret = '\'' + lib + '\''
  var f = readFileSync(`${lib}/configure.ac`, 'utf8').split(/AC_CONFIG_FILES/)
  if (f.length-1) {
    var line = f[1].match(/(\S.*?)include/gm)
    if (line) {
      ret += `,'${lib}/${line[0]}'`
      ret += `,'${lib}/${line[0]}/${lib.slice(3)}'`
    }
  }
  return ret
}

function cflags (o) {
  return '\'' + o.split('\n')
    .filter(i => /^CFLAGS/.test(i) || /^CPPFLAGS/.test(i) )
    .map(i => i.split("\'")[1].replace(/^\s+/g,''))
    .filter(i => i)
    .join('\',\'') + '\''
}

function ldflags (o) {
  return '\'' + o.split('\n')
    .filter(i => /^LDFLAGS/.test(i))
    .map(i => i.split("\'")[1].replace(/^\s+/g,''))
    .filter(i => i)
    .join('\',\'') + '\''
}

function defs (o) {
  return '\'' + o.split('\n')
    .filter(i => /define/.test(i))
    .map(i => i.slice(8).split(/\s/g).join('='))
    .filter(i => i)
    .join('\',\'') + '\''
}
```

Yesterday I began exploring the approach in experimental network library for distributed encrypted msgs:
https://github.com/reqshark/mill

> With a fixed version we can keep it working while we update, change, test newer versions of libsodium

when you say "fixed version" are you talking about node-sodium or libsodium?

**Comment by paixaop** [comment]
I mean lib sodium's version being fixed in time, and when we're sure a new version does not break anything move node-sodium to the new libsodium library.

The gyp generation tool is great. thanks for expanding upon it.

**Comment by reqshark** [comment]
Oh I might have now stumbled upon the reason I couldn't finish this PR earlier...

some files contain opcodes like for symbol `crypto_scalarmult_curve25519_sandy2x_ladder_base`.

these sources are [`built from assembly files`](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_scalarmult/curve25519/sandy2x/ladder_base.S) that end in `.S`, but gyp is able to compile them just fine, so I think it is now a matter of:
* listing any `.s` `.S` files in gyp sources array, and
* passing the AVX cflags, like `-mavx` or `-mavx2` accordingly, I have to put them in xcode_settings: `OTHER_CFLAGS` on osx, and plain `cflags` on linux (`cflags` of course doesnt work on osx)

**Comment by reqshark** [comment]
Oh by the way, lets close this PR

Ultimately while I think leaning on configure/make is a good way to build deps in a cross platform way as the library might have intended, it's still somewhat gnarly as a matter of npm installer business... So taking this stuff further might have been a step in the wrong direction. Also I'm not sure that npm supports git submodule inits in a clean way, or least that sort of thing seems to land outside of its preview as a subroutine of the install step

**Pull request closed without merging**
